// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module wsrsa1024_rsaModExp_Pipeline_VITIS_LOOP_8_11 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        conv_i11_i,
        zext_ln8,
        P_6_out,
        P_6_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [1023:0] conv_i11_i;
input  [1023:0] zext_ln8;
output  [1023:0] P_6_out;
output   P_6_out_ap_vld;

reg ap_idle;
reg P_6_out_ap_vld;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_pp0_stage1_subdone;
wire   [0:0] tmp_fu_92_p3;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [1026:0] zext_ln8_cast_fu_64_p1;
reg   [1026:0] zext_ln8_cast_reg_212;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
wire   [1027:0] conv_i11_i_cast_fu_68_p1;
reg   [1027:0] conv_i11_i_cast_reg_217;
reg   [11:0] i_2_reg_224;
wire    ap_block_pp0_stage1_11001;
wire   [1027:0] P_3_fu_120_p3;
reg   [1027:0] P_3_reg_232;
wire   [0:0] icmp_ln13_fu_128_p2;
reg   [0:0] icmp_ln13_reg_237;
wire   [1027:0] P_4_fu_133_p2;
reg   [1027:0] P_4_reg_242;
reg    ap_enable_reg_pp0_iter0_reg;
wire    ap_block_pp0_stage0_subdone;
wire    ap_block_pp0_stage1;
reg   [1026:0] P_fu_44;
wire   [1026:0] P_6_fu_169_p3;
wire    ap_loop_init;
reg   [11:0] i_fu_48;
wire   [11:0] i_3_fu_177_p2;
wire    ap_block_pp0_stage0;
wire   [1027:0] P_2_fu_100_p3;
wire   [0:0] icmp_ln11_fu_108_p2;
wire   [1027:0] or_ln12_fu_114_p2;
wire   [0:0] xor_ln13_fu_138_p2;
wire   [1027:0] P_5_fu_143_p3;
wire   [0:0] icmp_ln15_fu_153_p2;
wire   [1026:0] trunc_ln5_fu_149_p1;
wire   [0:0] xor_ln15_fu_158_p2;
wire   [1026:0] sub_ln16_fu_164_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_1to1;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

wsrsa1024_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_exit_pp0_iter0_stage1) | ((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            P_fu_44 <= 1027'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            P_fu_44 <= P_6_fu_169_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_fu_48 <= 12'd1024;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            i_fu_48 <= i_3_fu_177_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_fu_92_p3 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        P_3_reg_232 <= P_3_fu_120_p3;
        P_4_reg_242 <= P_4_fu_133_p2;
        icmp_ln13_reg_237 <= icmp_ln13_fu_128_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_i11_i_cast_reg_217[1023 : 0] <= conv_i11_i_cast_fu_68_p1[1023 : 0];
        zext_ln8_cast_reg_212[1023 : 0] <= zext_ln8_cast_fu_64_p1[1023 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        i_2_reg_224 <= i_fu_48;
    end
end

always @ (*) begin
    if (((tmp_fu_92_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        P_6_out_ap_vld = 1'b1;
    end else begin
        P_6_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_92_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign P_2_fu_100_p3 = {{P_fu_44}, {1'd0}};

assign P_3_fu_120_p3 = ((icmp_ln11_fu_108_p2[0:0] == 1'b1) ? or_ln12_fu_114_p2 : P_2_fu_100_p3);

assign P_4_fu_133_p2 = (P_3_fu_120_p3 - conv_i11_i_cast_reg_217);

assign P_5_fu_143_p3 = ((xor_ln13_fu_138_p2[0:0] == 1'b1) ? P_4_reg_242 : P_3_reg_232);

assign P_6_fu_169_p3 = ((xor_ln15_fu_158_p2[0:0] == 1'b1) ? sub_ln16_fu_164_p2 : trunc_ln5_fu_149_p1);

assign P_6_out = P_fu_44[1023:0];

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign conv_i11_i_cast_fu_68_p1 = conv_i11_i;

assign i_3_fu_177_p2 = ($signed(i_2_reg_224) + $signed(12'd4095));

assign icmp_ln11_fu_108_p2 = ((i_fu_48 == 12'd1024) ? 1'b1 : 1'b0);

assign icmp_ln13_fu_128_p2 = ((P_3_fu_120_p3 < conv_i11_i_cast_reg_217) ? 1'b1 : 1'b0);

assign icmp_ln15_fu_153_p2 = ((P_5_fu_143_p3 < conv_i11_i_cast_reg_217) ? 1'b1 : 1'b0);

assign or_ln12_fu_114_p2 = (1028'd1 | P_2_fu_100_p3);

assign sub_ln16_fu_164_p2 = (trunc_ln5_fu_149_p1 - zext_ln8_cast_reg_212);

assign tmp_fu_92_p3 = i_fu_48[32'd11];

assign trunc_ln5_fu_149_p1 = P_5_fu_143_p3[1026:0];

assign xor_ln13_fu_138_p2 = (icmp_ln13_reg_237 ^ 1'd1);

assign xor_ln15_fu_158_p2 = (icmp_ln15_fu_153_p2 ^ 1'd1);

assign zext_ln8_cast_fu_64_p1 = zext_ln8;

always @ (posedge ap_clk) begin
    zext_ln8_cast_reg_212[1026:1024] <= 3'b000;
    conv_i11_i_cast_reg_217[1027:1024] <= 4'b0000;
end

endmodule //wsrsa1024_rsaModExp_Pipeline_VITIS_LOOP_8_11
