// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module wsrsa1024_rsaModExp_Pipeline_VITIS_LOOP_16_12 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        X_1,
        zext_ln13_2,
        M,
        S_6_out,
        S_6_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [1023:0] X_1;
input  [1023:0] zext_ln13_2;
input  [1023:0] M;
output  [1024:0] S_6_out;
output   S_6_out_ap_vld;

reg ap_idle;
reg S_6_out_ap_vld;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_pp0_stage1_subdone;
wire   [0:0] icmp_ln16_fu_102_p2;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [1025:0] M_cast_fu_77_p1;
reg   [1025:0] M_cast_reg_208;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
wire   [1025:0] zext_ln13_2_cast_fu_81_p1;
reg   [1025:0] zext_ln13_2_cast_reg_213;
wire   [1025:0] X_1_cast_fu_85_p1;
reg   [1025:0] X_1_cast_reg_218;
wire   [1025:0] S_3_fu_137_p3;
reg   [1025:0] S_3_reg_226;
wire    ap_block_pp0_stage1_11001;
wire   [0:0] trunc_ln12_fu_145_p1;
reg   [0:0] trunc_ln12_reg_231;
reg   [1024:0] tmp_8_reg_236;
reg    ap_enable_reg_pp0_iter0_reg;
wire    ap_block_pp0_stage0_subdone;
reg   [1024:0] S_fu_44;
wire   [1024:0] select_ln22_fu_178_p3;
wire    ap_loop_init;
wire    ap_block_pp0_stage1;
reg   [10:0] i_fu_48;
wire   [10:0] i_9_fu_108_p2;
wire    ap_block_pp0_stage1_01001;
wire    ap_block_pp0_stage0;
wire   [31:0] i_8_cast_fu_121_p1;
wire   [1025:0] S_10_cast6_fu_117_p1;
wire   [0:0] bit_select_i13_i2_fu_125_p3;
wire   [1025:0] add_ln20_fu_132_p2;
wire   [1025:0] S_4_fu_164_p2;
wire   [1024:0] tmp_7_fu_168_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_1to1;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

wsrsa1024_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_exit_pp0_iter0_stage1) | ((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            S_fu_44 <= 1025'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            S_fu_44 <= select_ln22_fu_178_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_fu_48 <= 11'd0;
    end else if (((icmp_ln16_fu_102_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        i_fu_48 <= i_9_fu_108_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        M_cast_reg_208[1023 : 0] <= M_cast_fu_77_p1[1023 : 0];
        X_1_cast_reg_218[1023 : 0] <= X_1_cast_fu_85_p1[1023 : 0];
        zext_ln13_2_cast_reg_213[1023 : 0] <= zext_ln13_2_cast_fu_81_p1[1023 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln16_fu_102_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        S_3_reg_226 <= S_3_fu_137_p3;
        tmp_8_reg_236 <= {{S_3_fu_137_p3[1025:1]}};
        trunc_ln12_reg_231 <= trunc_ln12_fu_145_p1;
    end
end

always @ (*) begin
    if (((icmp_ln16_fu_102_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        S_6_out_ap_vld = 1'b1;
    end else begin
        S_6_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln16_fu_102_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign M_cast_fu_77_p1 = M;

assign S_10_cast6_fu_117_p1 = S_fu_44;

assign S_3_fu_137_p3 = ((bit_select_i13_i2_fu_125_p3[0:0] == 1'b1) ? add_ln20_fu_132_p2 : S_10_cast6_fu_117_p1);

assign S_4_fu_164_p2 = (S_3_reg_226 + M_cast_reg_208);

assign S_6_out = S_fu_44;

assign X_1_cast_fu_85_p1 = X_1;

assign add_ln20_fu_132_p2 = (S_10_cast6_fu_117_p1 + zext_ln13_2_cast_reg_213);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign bit_select_i13_i2_fu_125_p3 = X_1_cast_reg_218[i_8_cast_fu_121_p1];

assign i_8_cast_fu_121_p1 = i_fu_48;

assign i_9_fu_108_p2 = (i_fu_48 + 11'd1);

assign icmp_ln16_fu_102_p2 = ((i_fu_48 == 11'd1024) ? 1'b1 : 1'b0);

assign select_ln22_fu_178_p3 = ((trunc_ln12_reg_231[0:0] == 1'b1) ? tmp_7_fu_168_p4 : tmp_8_reg_236);

assign tmp_7_fu_168_p4 = {{S_4_fu_164_p2[1025:1]}};

assign trunc_ln12_fu_145_p1 = S_3_fu_137_p3[0:0];

assign zext_ln13_2_cast_fu_81_p1 = zext_ln13_2;

always @ (posedge ap_clk) begin
    M_cast_reg_208[1025:1024] <= 2'b00;
    zext_ln13_2_cast_reg_213[1025:1024] <= 2'b00;
    X_1_cast_reg_218[1025:1024] <= 2'b00;
end

endmodule //wsrsa1024_rsaModExp_Pipeline_VITIS_LOOP_16_12
