// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module wsrsa1024_rsaModExp (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        M_val,
        e_val,
        n_val,
        ap_return
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_state4 = 10'd8;
parameter    ap_ST_fsm_state5 = 10'd16;
parameter    ap_ST_fsm_state6 = 10'd32;
parameter    ap_ST_fsm_state7 = 10'd64;
parameter    ap_ST_fsm_state8 = 10'd128;
parameter    ap_ST_fsm_state9 = 10'd256;
parameter    ap_ST_fsm_state10 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [1023:0] M_val;
input  [1023:0] e_val;
input  [1023:0] n_val;
output  [1023:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [1023:0] reg_142;
wire    ap_CS_fsm_state4;
wire   [0:0] tmp_fu_162_p3;
wire    ap_CS_fsm_state3;
wire   [1024:0] n_val_cast1_fu_156_p1;
reg   [1024:0] n_val_cast1_reg_371;
wire   [0:0] icmp_ln30_fu_189_p2;
reg   [0:0] icmp_ln30_reg_384;
wire   [1023:0] xbar_2_fu_218_p3;
reg   [1023:0] xbar_2_reg_388;
wire    ap_CS_fsm_state6;
wire    grp_rsaModExp_Pipeline_VITIS_LOOP_8_1_fu_95_ap_start;
wire    grp_rsaModExp_Pipeline_VITIS_LOOP_8_1_fu_95_ap_done;
wire    grp_rsaModExp_Pipeline_VITIS_LOOP_8_1_fu_95_ap_idle;
wire    grp_rsaModExp_Pipeline_VITIS_LOOP_8_1_fu_95_ap_ready;
wire   [1023:0] grp_rsaModExp_Pipeline_VITIS_LOOP_8_1_fu_95_P_out;
wire    grp_rsaModExp_Pipeline_VITIS_LOOP_8_1_fu_95_P_out_ap_vld;
wire    grp_rsaModExp_Pipeline_VITIS_LOOP_8_11_fu_106_ap_start;
wire    grp_rsaModExp_Pipeline_VITIS_LOOP_8_11_fu_106_ap_done;
wire    grp_rsaModExp_Pipeline_VITIS_LOOP_8_11_fu_106_ap_idle;
wire    grp_rsaModExp_Pipeline_VITIS_LOOP_8_11_fu_106_ap_ready;
wire   [1023:0] grp_rsaModExp_Pipeline_VITIS_LOOP_8_11_fu_106_P_6_out;
wire    grp_rsaModExp_Pipeline_VITIS_LOOP_8_11_fu_106_P_6_out_ap_vld;
wire    grp_rsaModExp_Pipeline_VITIS_LOOP_16_1_fu_115_ap_start;
wire    grp_rsaModExp_Pipeline_VITIS_LOOP_16_1_fu_115_ap_done;
wire    grp_rsaModExp_Pipeline_VITIS_LOOP_16_1_fu_115_ap_idle;
wire    grp_rsaModExp_Pipeline_VITIS_LOOP_16_1_fu_115_ap_ready;
wire   [1024:0] grp_rsaModExp_Pipeline_VITIS_LOOP_16_1_fu_115_S_out;
wire    grp_rsaModExp_Pipeline_VITIS_LOOP_16_1_fu_115_S_out_ap_vld;
wire    grp_rsaModExp_Pipeline_VITIS_LOOP_16_13_fu_122_ap_start;
wire    grp_rsaModExp_Pipeline_VITIS_LOOP_16_13_fu_122_ap_done;
wire    grp_rsaModExp_Pipeline_VITIS_LOOP_16_13_fu_122_ap_idle;
wire    grp_rsaModExp_Pipeline_VITIS_LOOP_16_13_fu_122_ap_ready;
wire   [1024:0] grp_rsaModExp_Pipeline_VITIS_LOOP_16_13_fu_122_S_3_out;
wire    grp_rsaModExp_Pipeline_VITIS_LOOP_16_13_fu_122_S_3_out_ap_vld;
wire    grp_rsaModExp_Pipeline_VITIS_LOOP_16_12_fu_129_ap_start;
wire    grp_rsaModExp_Pipeline_VITIS_LOOP_16_12_fu_129_ap_done;
wire    grp_rsaModExp_Pipeline_VITIS_LOOP_16_12_fu_129_ap_idle;
wire    grp_rsaModExp_Pipeline_VITIS_LOOP_16_12_fu_129_ap_ready;
wire   [1024:0] grp_rsaModExp_Pipeline_VITIS_LOOP_16_12_fu_129_S_6_out;
wire    grp_rsaModExp_Pipeline_VITIS_LOOP_16_12_fu_129_S_6_out_ap_vld;
wire   [1023:0] xbar_fu_250_p3;
reg   [1023:0] ap_phi_mux_xbar_1_phi_fu_89_p4;
reg   [1023:0] xbar_1_reg_86;
wire    ap_CS_fsm_state8;
reg    grp_rsaModExp_Pipeline_VITIS_LOOP_8_1_fu_95_ap_start_reg;
wire    ap_CS_fsm_state2;
reg   [1023:0] P_loc_fu_64;
reg    grp_rsaModExp_Pipeline_VITIS_LOOP_8_11_fu_106_ap_start_reg;
reg   [1023:0] X_fu_48;
reg    grp_rsaModExp_Pipeline_VITIS_LOOP_16_1_fu_115_ap_start_reg;
wire    ap_CS_fsm_state5;
reg    grp_rsaModExp_Pipeline_VITIS_LOOP_16_13_fu_122_ap_start_reg;
wire    ap_CS_fsm_state9;
reg    grp_rsaModExp_Pipeline_VITIS_LOOP_16_12_fu_129_ap_start_reg;
wire    ap_CS_fsm_state7;
reg   [10:0] i_01_fu_44;
wire   [10:0] i_11_fu_259_p2;
wire    ap_CS_fsm_state10;
wire   [9:0] trunc_ln30_fu_170_p1;
wire   [1023:0] zext_ln30_fu_174_p1;
wire   [1023:0] shl_ln30_fu_178_p2;
wire   [1023:0] and_ln30_fu_184_p2;
wire   [0:0] icmp_ln29_1_fu_202_p2;
wire   [1023:0] empty_fu_198_p1;
wire   [0:0] xor_ln29_1_fu_207_p2;
wire   [1023:0] sub_ln31_fu_213_p2;
wire   [0:0] icmp_ln29_2_fu_234_p2;
wire   [1023:0] empty_17_fu_230_p1;
wire   [0:0] xor_ln29_2_fu_239_p2;
wire   [1023:0] sub_ln31_2_fu_245_p2;
wire   [0:0] icmp_ln29_fu_281_p2;
wire   [1023:0] empty_18_fu_277_p1;
wire   [0:0] xor_ln29_fu_286_p2;
wire   [1023:0] sub_ln31_1_fu_292_p2;
reg   [9:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_block_state2_on_subcall_done;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 10'd1;
#0 grp_rsaModExp_Pipeline_VITIS_LOOP_8_1_fu_95_ap_start_reg = 1'b0;
#0 grp_rsaModExp_Pipeline_VITIS_LOOP_8_11_fu_106_ap_start_reg = 1'b0;
#0 grp_rsaModExp_Pipeline_VITIS_LOOP_16_1_fu_115_ap_start_reg = 1'b0;
#0 grp_rsaModExp_Pipeline_VITIS_LOOP_16_13_fu_122_ap_start_reg = 1'b0;
#0 grp_rsaModExp_Pipeline_VITIS_LOOP_16_12_fu_129_ap_start_reg = 1'b0;
end

wsrsa1024_rsaModExp_Pipeline_VITIS_LOOP_8_1 grp_rsaModExp_Pipeline_VITIS_LOOP_8_1_fu_95(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_rsaModExp_Pipeline_VITIS_LOOP_8_1_fu_95_ap_start),
    .ap_done(grp_rsaModExp_Pipeline_VITIS_LOOP_8_1_fu_95_ap_done),
    .ap_idle(grp_rsaModExp_Pipeline_VITIS_LOOP_8_1_fu_95_ap_idle),
    .ap_ready(grp_rsaModExp_Pipeline_VITIS_LOOP_8_1_fu_95_ap_ready),
    .conv_i14_i(M_val),
    .conv_i11_i(n_val),
    .zext_ln8(n_val),
    .P_out(grp_rsaModExp_Pipeline_VITIS_LOOP_8_1_fu_95_P_out),
    .P_out_ap_vld(grp_rsaModExp_Pipeline_VITIS_LOOP_8_1_fu_95_P_out_ap_vld)
);

wsrsa1024_rsaModExp_Pipeline_VITIS_LOOP_8_11 grp_rsaModExp_Pipeline_VITIS_LOOP_8_11_fu_106(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_rsaModExp_Pipeline_VITIS_LOOP_8_11_fu_106_ap_start),
    .ap_done(grp_rsaModExp_Pipeline_VITIS_LOOP_8_11_fu_106_ap_done),
    .ap_idle(grp_rsaModExp_Pipeline_VITIS_LOOP_8_11_fu_106_ap_idle),
    .ap_ready(grp_rsaModExp_Pipeline_VITIS_LOOP_8_11_fu_106_ap_ready),
    .conv_i11_i(n_val),
    .zext_ln8(n_val),
    .P_6_out(grp_rsaModExp_Pipeline_VITIS_LOOP_8_11_fu_106_P_6_out),
    .P_6_out_ap_vld(grp_rsaModExp_Pipeline_VITIS_LOOP_8_11_fu_106_P_6_out_ap_vld)
);

wsrsa1024_rsaModExp_Pipeline_VITIS_LOOP_16_1 grp_rsaModExp_Pipeline_VITIS_LOOP_16_1_fu_115(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_rsaModExp_Pipeline_VITIS_LOOP_16_1_fu_115_ap_start),
    .ap_done(grp_rsaModExp_Pipeline_VITIS_LOOP_16_1_fu_115_ap_done),
    .ap_idle(grp_rsaModExp_Pipeline_VITIS_LOOP_16_1_fu_115_ap_idle),
    .ap_ready(grp_rsaModExp_Pipeline_VITIS_LOOP_16_1_fu_115_ap_ready),
    .zext_ln13(reg_142),
    .M(n_val),
    .S_out(grp_rsaModExp_Pipeline_VITIS_LOOP_16_1_fu_115_S_out),
    .S_out_ap_vld(grp_rsaModExp_Pipeline_VITIS_LOOP_16_1_fu_115_S_out_ap_vld)
);

wsrsa1024_rsaModExp_Pipeline_VITIS_LOOP_16_13 grp_rsaModExp_Pipeline_VITIS_LOOP_16_13_fu_122(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_rsaModExp_Pipeline_VITIS_LOOP_16_13_fu_122_ap_start),
    .ap_done(grp_rsaModExp_Pipeline_VITIS_LOOP_16_13_fu_122_ap_done),
    .ap_idle(grp_rsaModExp_Pipeline_VITIS_LOOP_16_13_fu_122_ap_idle),
    .ap_ready(grp_rsaModExp_Pipeline_VITIS_LOOP_16_13_fu_122_ap_ready),
    .zext_ln13_1(reg_142),
    .M(n_val),
    .S_3_out(grp_rsaModExp_Pipeline_VITIS_LOOP_16_13_fu_122_S_3_out),
    .S_3_out_ap_vld(grp_rsaModExp_Pipeline_VITIS_LOOP_16_13_fu_122_S_3_out_ap_vld)
);

wsrsa1024_rsaModExp_Pipeline_VITIS_LOOP_16_12 grp_rsaModExp_Pipeline_VITIS_LOOP_16_12_fu_129(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_rsaModExp_Pipeline_VITIS_LOOP_16_12_fu_129_ap_start),
    .ap_done(grp_rsaModExp_Pipeline_VITIS_LOOP_16_12_fu_129_ap_done),
    .ap_idle(grp_rsaModExp_Pipeline_VITIS_LOOP_16_12_fu_129_ap_idle),
    .ap_ready(grp_rsaModExp_Pipeline_VITIS_LOOP_16_12_fu_129_ap_ready),
    .X_1(P_loc_fu_64),
    .zext_ln13_2(xbar_2_reg_388),
    .M(n_val),
    .S_6_out(grp_rsaModExp_Pipeline_VITIS_LOOP_16_12_fu_129_S_6_out),
    .S_6_out_ap_vld(grp_rsaModExp_Pipeline_VITIS_LOOP_16_12_fu_129_S_6_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_rsaModExp_Pipeline_VITIS_LOOP_16_12_fu_129_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln30_reg_384 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
            grp_rsaModExp_Pipeline_VITIS_LOOP_16_12_fu_129_ap_start_reg <= 1'b1;
        end else if ((grp_rsaModExp_Pipeline_VITIS_LOOP_16_12_fu_129_ap_ready == 1'b1)) begin
            grp_rsaModExp_Pipeline_VITIS_LOOP_16_12_fu_129_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_rsaModExp_Pipeline_VITIS_LOOP_16_13_fu_122_ap_start_reg <= 1'b0;
    end else begin
        if (((tmp_fu_162_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
            grp_rsaModExp_Pipeline_VITIS_LOOP_16_13_fu_122_ap_start_reg <= 1'b1;
        end else if ((grp_rsaModExp_Pipeline_VITIS_LOOP_16_13_fu_122_ap_ready == 1'b1)) begin
            grp_rsaModExp_Pipeline_VITIS_LOOP_16_13_fu_122_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_rsaModExp_Pipeline_VITIS_LOOP_16_1_fu_115_ap_start_reg <= 1'b0;
    end else begin
        if (((tmp_fu_162_p3 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
            grp_rsaModExp_Pipeline_VITIS_LOOP_16_1_fu_115_ap_start_reg <= 1'b1;
        end else if ((grp_rsaModExp_Pipeline_VITIS_LOOP_16_1_fu_115_ap_ready == 1'b1)) begin
            grp_rsaModExp_Pipeline_VITIS_LOOP_16_1_fu_115_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_rsaModExp_Pipeline_VITIS_LOOP_8_11_fu_106_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_rsaModExp_Pipeline_VITIS_LOOP_8_11_fu_106_ap_start_reg <= 1'b1;
        end else if ((grp_rsaModExp_Pipeline_VITIS_LOOP_8_11_fu_106_ap_ready == 1'b1)) begin
            grp_rsaModExp_Pipeline_VITIS_LOOP_8_11_fu_106_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_rsaModExp_Pipeline_VITIS_LOOP_8_1_fu_95_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_rsaModExp_Pipeline_VITIS_LOOP_8_1_fu_95_ap_start_reg <= 1'b1;
        end else if ((grp_rsaModExp_Pipeline_VITIS_LOOP_8_1_fu_95_ap_ready == 1'b1)) begin
            grp_rsaModExp_Pipeline_VITIS_LOOP_8_1_fu_95_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        X_fu_48 <= ap_phi_mux_xbar_1_phi_fu_89_p4;
    end else if (((grp_rsaModExp_Pipeline_VITIS_LOOP_8_11_fu_106_P_6_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        X_fu_48 <= grp_rsaModExp_Pipeline_VITIS_LOOP_8_11_fu_106_P_6_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_01_fu_44 <= 11'd1023;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        i_01_fu_44 <= i_11_fu_259_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln30_reg_384 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        xbar_1_reg_86 <= xbar_2_fu_218_p3;
    end else if (((icmp_ln30_reg_384 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        xbar_1_reg_86 <= xbar_fu_250_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_rsaModExp_Pipeline_VITIS_LOOP_8_1_fu_95_P_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        P_loc_fu_64 <= grp_rsaModExp_Pipeline_VITIS_LOOP_8_1_fu_95_P_out;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_fu_162_p3 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        icmp_ln30_reg_384 <= icmp_ln30_fu_189_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        n_val_cast1_reg_371[1023 : 0] <= n_val_cast1_fu_156_p1[1023 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((((tmp_fu_162_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state4)) | ((tmp_fu_162_p3 == 1'd0) & (1'b1 == ap_CS_fsm_state4)))) begin
        reg_142 <= X_fu_48;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        xbar_2_reg_388 <= xbar_2_fu_218_p3;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_on_subcall_done)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_rsaModExp_Pipeline_VITIS_LOOP_16_1_fu_115_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_rsaModExp_Pipeline_VITIS_LOOP_16_12_fu_129_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((grp_rsaModExp_Pipeline_VITIS_LOOP_16_13_fu_122_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln30_reg_384 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        ap_phi_mux_xbar_1_phi_fu_89_p4 = xbar_fu_250_p3;
    end else begin
        ap_phi_mux_xbar_1_phi_fu_89_p4 = xbar_1_reg_86;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((tmp_fu_162_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((grp_rsaModExp_Pipeline_VITIS_LOOP_16_1_fu_115_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((icmp_ln30_reg_384 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (grp_rsaModExp_Pipeline_VITIS_LOOP_16_12_fu_129_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state9 : begin
            if (((1'b1 == ap_CS_fsm_state9) & (grp_rsaModExp_Pipeline_VITIS_LOOP_16_13_fu_122_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign and_ln30_fu_184_p2 = (shl_ln30_fu_178_p2 & e_val);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state2_on_subcall_done = ((grp_rsaModExp_Pipeline_VITIS_LOOP_8_11_fu_106_ap_done == 1'b0) | (grp_rsaModExp_Pipeline_VITIS_LOOP_8_1_fu_95_ap_done == 1'b0));
end

assign ap_return = ((xor_ln29_fu_286_p2[0:0] == 1'b1) ? sub_ln31_1_fu_292_p2 : empty_18_fu_277_p1);

assign empty_17_fu_230_p1 = grp_rsaModExp_Pipeline_VITIS_LOOP_16_12_fu_129_S_6_out[1023:0];

assign empty_18_fu_277_p1 = grp_rsaModExp_Pipeline_VITIS_LOOP_16_13_fu_122_S_3_out[1023:0];

assign empty_fu_198_p1 = grp_rsaModExp_Pipeline_VITIS_LOOP_16_1_fu_115_S_out[1023:0];

assign grp_rsaModExp_Pipeline_VITIS_LOOP_16_12_fu_129_ap_start = grp_rsaModExp_Pipeline_VITIS_LOOP_16_12_fu_129_ap_start_reg;

assign grp_rsaModExp_Pipeline_VITIS_LOOP_16_13_fu_122_ap_start = grp_rsaModExp_Pipeline_VITIS_LOOP_16_13_fu_122_ap_start_reg;

assign grp_rsaModExp_Pipeline_VITIS_LOOP_16_1_fu_115_ap_start = grp_rsaModExp_Pipeline_VITIS_LOOP_16_1_fu_115_ap_start_reg;

assign grp_rsaModExp_Pipeline_VITIS_LOOP_8_11_fu_106_ap_start = grp_rsaModExp_Pipeline_VITIS_LOOP_8_11_fu_106_ap_start_reg;

assign grp_rsaModExp_Pipeline_VITIS_LOOP_8_1_fu_95_ap_start = grp_rsaModExp_Pipeline_VITIS_LOOP_8_1_fu_95_ap_start_reg;

assign i_11_fu_259_p2 = ($signed(i_01_fu_44) + $signed(11'd2047));

assign icmp_ln29_1_fu_202_p2 = ((grp_rsaModExp_Pipeline_VITIS_LOOP_16_1_fu_115_S_out < n_val_cast1_reg_371) ? 1'b1 : 1'b0);

assign icmp_ln29_2_fu_234_p2 = ((grp_rsaModExp_Pipeline_VITIS_LOOP_16_12_fu_129_S_6_out < n_val_cast1_reg_371) ? 1'b1 : 1'b0);

assign icmp_ln29_fu_281_p2 = ((grp_rsaModExp_Pipeline_VITIS_LOOP_16_13_fu_122_S_3_out < n_val_cast1_reg_371) ? 1'b1 : 1'b0);

assign icmp_ln30_fu_189_p2 = ((and_ln30_fu_184_p2 == 1024'd0) ? 1'b1 : 1'b0);

assign n_val_cast1_fu_156_p1 = n_val;

assign shl_ln30_fu_178_p2 = 1024'd1 << zext_ln30_fu_174_p1;

assign sub_ln31_1_fu_292_p2 = (empty_18_fu_277_p1 - n_val);

assign sub_ln31_2_fu_245_p2 = (empty_17_fu_230_p1 - n_val);

assign sub_ln31_fu_213_p2 = (empty_fu_198_p1 - n_val);

assign tmp_fu_162_p3 = i_01_fu_44[32'd10];

assign trunc_ln30_fu_170_p1 = i_01_fu_44[9:0];

assign xbar_2_fu_218_p3 = ((xor_ln29_1_fu_207_p2[0:0] == 1'b1) ? sub_ln31_fu_213_p2 : empty_fu_198_p1);

assign xbar_fu_250_p3 = ((xor_ln29_2_fu_239_p2[0:0] == 1'b1) ? sub_ln31_2_fu_245_p2 : empty_17_fu_230_p1);

assign xor_ln29_1_fu_207_p2 = (icmp_ln29_1_fu_202_p2 ^ 1'd1);

assign xor_ln29_2_fu_239_p2 = (icmp_ln29_2_fu_234_p2 ^ 1'd1);

assign xor_ln29_fu_286_p2 = (icmp_ln29_fu_281_p2 ^ 1'd1);

assign zext_ln30_fu_174_p1 = trunc_ln30_fu_170_p1;

always @ (posedge ap_clk) begin
    n_val_cast1_reg_371[1024] <= 1'b0;
end

endmodule //wsrsa1024_rsaModExp
